// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhzkkrhxaqbryxzzbgbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoemtrcmh4YXFicnl4enpiZ2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzM5MDIsImV4cCI6MjA2NjQwOTkwMn0.vVa5xfFFnneAz2UYHoPZfCwe5DyXXs_xnCD5tDqmUcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);